# Generated by Django 2.2.4 on 2021-04-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_auto_20210422_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='genre',
            new_name='genere',
        ),
    ]
