# Generated by Django 2.2.4 on 2021-04-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0003_auto_20210422_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
