# Generated by Django 2.2.4 on 2021-04-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0004_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='poorly_coded_store.Product'),
            preserve_default=False,
        ),
    ]
