# Generated by Django 2.2.4 on 2021-04-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0006_auto_20210422_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='oder',
        ),
    ]
